### ISSUE TITLE
Health bar not updating properly

### ISSUE THREAD

**Issue by manskou** [manskou/Nerfus-Metera-issues#4] opened 2018-02-09 11:46 UTC
Health bar stays at 100% at all times.

Cannot reproduce in Bluestacks on build 0.3.19
Cannot reproduce in my phone on build 0.3.19

**Comment by AngeloGi** [comment] 2018-02-09 18:37
Attempt Fixing at build 0.3.20.

**Comment by manskou** [comment] 2018-02-09 21:41
problem presists at build 0.3.20

**Comment by MariaXri** [comment] 2018-02-10 10:12
![screenshot_20180210-120806](https://user-images.githubusercontent.com/36327676/36060936-7effac54-0e5b-11e8-968f-4c2176eaca2b.png)
0.3.21

**Comment by manskou** [comment] 2018-02-10 11:25
have you tried clearing the save and/or [deleting the game's data?](https://www.androidcentral.com/how-and-when-clear-app-cache-or-data-android) 

could be some weird remnant from a save from an old build

**Comment by MariaXri** [comment] 2018-02-10 12:01
cleared app's data, deleted the app completely and installed again, restarted the device and it still remains the same

**Comment by AngeloGi** [comment] 2018-02-10 12:02
Try format C:/ (no seriously I have no idea what the problem is, I'll come
back to it later)

**Comment by MariaXri** [comment] 2018-02-10 18:25
![screenshot_20180210-202235](https://user-images.githubusercontent.com/36327676/36065224-72518b36-0ea0-11e8-8aa5-70e7119da47f.jpg) Metera-armv7-es2.apk

**Comment by AngeloGi** [comment] 2018-02-13 15:48
Check for fix in v0.3.22
.

**Comment by AngeloGi** [comment] 2018-02-13 22:11
Issue persists, UE4 Engine bug, closing for now until future updates.

**Closed as completed by AngeloGi** 2018-02-13 22:11 UTC
Labels: high priority
