### ISSUE TITLE
Wrong wave count?

### ISSUE THREAD

**Issue by DionisisR** [manskou/Nerfus-Metera-issues#20] opened 2018-05-11 18:05 UTC
According to GDD sheets there are 20 waves. After about 10-12 waves the progress bar is still very low. Might be the same problem as issue #19

**Comment by PwnzorBot4000** [comment] 2018-05-15 07:40
Seems fixed in latest development build. Indeed duplicate of #19 .

**Closed as completed** 2018-05-15 14:22 UTC
Labels: duplicate, question, awaiting feedback
